# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchFromGitHub, ... }:

buildGoPackage rec {
  name = "gliderlabs-sigil-${version}";
  version = "0.4.0";
  rev = "v${version}";

  goPackagePath = "github.com/gliderlabs/sigil";

  src = fetchFromGitHub {
    inherit rev;
    owner = "gliderlabs";
    repo = "sigil";
    sha256 = "0jacnl516mxn3rv8cd6xby2zhi0i0qhp5lgv019sx23b7spwjdfs";
  };

  buildFlagsArray = [ "-ldflags=" "-X main.Version=${rev}" ];

  postInstall = ''
    mv $bin/bin/cmd $bin/bin/sigil
  '';

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    homepage = http://gliderlabs.github.io/devlog/;
    description = "Standalone string interpolator and template processor";
    license = licenses.bsd3;
    platforms = platforms.linux;
    maintainers = with maintainers; [
      WhittlesJr
    ];
  };
}
