# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
# Run go2nix from /builtins to get full list of dependencies
[
  {
    goPackagePath = "github.com/dustin/go-jsonpointer";
    fetch = {
      type = "git";
      url = "https://github.com/dustin/go-jsonpointer";
      rev = "ba0abeacc3dcca5b9b20f31509c46794edbc9965";
      sha256 = "109v4pw2aycxwyfs7g4yld36phxd6zibls9d6kmdkm6v4x4kdw9d";
    };
  }
  {
    goPackagePath = "github.com/dustin/gojson";
    fetch = {
      type = "git";
      url = "https://github.com/dustin/gojson";
      rev = "2e71ec9dd5adce3b168cd0dbde03b5cc04951c30";
      sha256 = "1vrmmyn7l568l1k71mxd54iqf3d54pn86cf278i374j86jn0bdxf";
    };
  }
  {
    goPackagePath = "github.com/flynn/go-shlex";
    fetch = {
      type = "git";
      url = "https://github.com/flynn/go-shlex";
      rev = "3f9db97f856818214da2e1057f8ad84803971cff";
      sha256 = "1j743lysygkpa2s2gii2xr32j7bxgc15zv4113b0q9jhn676ysia";
    };
  }
  {
    goPackagePath = "github.com/jmespath/go-jmespath";
    fetch = {
      type = "git";
      url = "https://github.com/jmespath/go-jmespath";
      rev = "c2b33e8439af944379acbdd9c3a5fe0bc44bd8a5";
      sha256 = "1r6w7ydx8ydryxk3sfhzsk8m6f1nsik9jg3i1zhi69v4kfl4d5cz";
    };
  }
  {
    goPackagePath = "github.com/mgood/go-posix";
    fetch = {
      type = "git";
      url = "https://github.com/mgood/go-posix";
      rev = "948c005421f5d716f5d89cd8940e722240713663";
      sha256 = "1z6f8kkshnr5s8d1g8w4zxnzry88hy4srz27wna9afixg66rrl55";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "51d6538a90f86fe93ac480b35f37b2be17fef232";
      sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa";
    };
  }

]
