# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "tsuru-${version}";
  version = "1.6.2";
  rev = "${version}";

  goPackagePath = "github.com/tsuru/tsuru";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/tsuru/tsuru.git";
    sha256 = "0290idilij5ik5lg16s0b79zhda46p331v9r2dbqrjvjhfvw4lg4";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    homepage = https://docs.tsuru.io;
    description = "Open source, extensible and Docker-based Platform as a Service (PaaS).";
    license = licenses.bsd-3;
    platforms = platforms.linux;
    maintainers = with maintainers; [
      WhittlesJr
    ];
  };
}
