# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/PuerkitoBio/purell";
    fetch = {
      type = "git";
      url = "https://github.com/PuerkitoBio/purell";
      rev = "975f53781597ed779763b7b65566e74c4004d8de";
      sha256 = "1j5l793zxrjv09z3cdgs05qn45sbhbm9njsw5cfv168x8z88pd3l";
    };
  }
  {
    goPackagePath = "github.com/PuerkitoBio/urlesc";
    fetch = {
      type = "git";
      url = "https://github.com/PuerkitoBio/urlesc";
      rev = "de5bf2ad457846296e2031421a34e2568e304e35";
      sha256 = "0n0srpqwbaan1wrhh2b7ysz543pjs1xw2rghvqyffg9l0g8kzgcw";
    };
  }
  {
    goPackagePath = "github.com/docopt/docopt-go";
    fetch = {
      type = "git";
      url = "https://github.com/docopt/docopt-go";
      rev = "ee0de3bc6815ee19d4a46c7eb90f829db0e014b1";
      sha256 = "0hlra7rmi5pmd7d93rv56ahiy4qkgmq8a6mz0jpadvbi5qh8lq6j";
    };
  }
  {
    goPackagePath = "github.com/goware/urlx";
    fetch = {
      type = "git";
      url = "https://github.com/goware/urlx";
      rev = "06d8eeb3ce171b5617a3f8ef24451df26ca971ef";
      sha256 = "03wwk144hjvjvf8qhh62rd6p2gjhra23czjkp7vakpahi226qwri";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "703b5e6b11ae25aeb2af9ebb5d5fdf8fa2575211";
      sha256 = "0znpyz71gajx3g0j2zp63nhjj2c07g16885vxv4ykwnrfmzbgk4w";
    };
  }
  {
    goPackagePath = "github.com/olekukonko/tablewriter";
    fetch = {
      type = "git";
      url = "https://github.com/olekukonko/tablewriter";
      rev = "e6d60cf7ba1f42d86d54cdf5508611c4aafb3970";
      sha256 = "0hh95glg7d2md185r03wn52j2r33jc4zil0qvcrs66ka7bdxi7vj";
    };
  }
  {
    goPackagePath = "github.com/teamhephy/controller-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/teamhephy/controller-sdk-go";
      rev = "a1ffb4886a5f7f92fdd710b99e68c2555b74a703";
      sha256 = "0iafp61gblgbp4j2ykka8b0h9f0zbqh4d32360w028qxhxk5i836";
    };
  }
  {
    goPackagePath = "github.com/teamhephy/pkg";
    fetch = {
      type = "git";
      url = "https://github.com/teamhephy/pkg";
      rev = "777f37a30108edaf6a2bd4e423cde34ec12870fd";
      sha256 = "15v9ascqillg11iifzsgqycpylcgnfsvyaqbnlhy11b3ffgasgx0";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "74369b46fc6756741c016591724fd1cb8e26845f";
      sha256 = "0zfc540yrkyl85x9ps4d6s31qpazm4k8vmsy2r66wwaj2c0mw4z7";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "3a22650c66bd7f4fb6d1e8072ffd7b75c8a27898";
      sha256 = "12q6fgdkc0742vcms67nzadgdwvi3rnb1gx3vwkljhrvlnwvz7wc";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "983097b1a8a340cd1cc7df17d735154d89e10b1a";
      sha256 = "0n2i2fsxj6pqp94yjnav8xp1ydpnwmzzfrmap9chahfjpwgrq62r";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "6c92c7dc7f53607809182301b96e4cc1975143f1";
      sha256 = "0pkdvzn0gdkl1s04z2i3blg4v1jsihbspvdqwa8ngdgjxbndxijq";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "51d6538a90f86fe93ac480b35f37b2be17fef232";
      sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa";
    };
  }
]
