# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ pkgs, stdenv, buildGoPackage, fetchFromGitHub, ... }:

buildGoPackage rec {
  name = "plugn-${version}";
  version = "0.3.0";
  rev = "v${version}";

  goPackagePath = "github.com/jteeuwen/dokku/plugn";

  src = fetchFromGitHub {
    inherit rev;
    owner = "dokku";
    repo = "plugn";
    sha256 = "1j5wjihv8k3ay1lrdxhslscs612r80f7rbzkvc4mg3g8flkm8ana";
  };

  buildFlagsArray = [ "-ldflags=" "-X main.Version=${rev}" ];
  buildInputs = [ pkgs.go-bindata ];

  preBuild = ''
    cd go/src/${goPackagePath}

    go-bindata bashenv
  '';

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    homepage = https://github.com/dokku/plugn;
    description = "Hook system that lets users extend your application with plugins";
    license = licenses.mit;
    platforms = platforms.linux;
    maintainers = with maintainers; [
      WhittlesJr
    ];
  };
}
