# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "planb-${version}";
  version = "0.1.13";
  rev = "${version}";

  goPackagePath = "github.com/tsuru/planb";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/tsuru/planb.git";
    sha256 = "1s0cdccil1ilh0kf232zjl356pp04b7wyk6ww2il99b6v0bpks78";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    homepage = https://docs.tsuru.io;
    description = "A distributed HTTP and websocket proxy inspired by Hipache";
    license = licenses.bsd-3;
    platforms = platforms.linux;
    maintainers = with maintainers; [
      WhittlesJr
    ];
  };
}
