# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchFromGitHub, ... }:

buildGoPackage rec {
  name = "procfile-util-${version}";
  version = "0.4.0";
  rev = "v${version}";

  goPackagePath = "github.com/josegonzalez/go-procfile-util";

  src = fetchFromGitHub {
    inherit rev;
    owner = "josegonzalez";
    repo = "go-procfile-util";
    sha256 = "183l2kicps31vrvrq1cb5bi5qxfn053dp19inxsgkcgshx1msbrg";
  };

  buildFlagsArray = [ "-ldflags=" "-X main.Version=${rev}" ];

  postInstall = ''
    mv $bin/bin/go-procfile-util $bin/bin/procfile-util
  '';

  meta = with stdenv.lib; {
    homepage = https://github.com/josegonzalez/go-procfile-util;
    description = "A tool for interacting with Procfiles";
    license = licenses.mit;
    platforms = platforms.linux;
    maintainers = with maintainers; [
      WhittlesJr
    ];
  };
}
