# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ pkgs, stdenv, buildGoPackage, fetchFromGitHub, ... }:

buildGoPackage rec {
  name = "herokuish-${version}";
  version = "0.4.7";
  rev = "v${version}";

  goPackagePath = "github.com/gliderlabs/herokuish";

  src = fetchFromGitHub {
    inherit rev;
    owner = "gliderlabs";
    repo = "herokuish";
    sha256 = "04qqr32lwg68nmlyzsb9ligyigqbz6hf4a96b3dpcjdylgb8pqij";
  };

  buildFlagsArray = [ "-ldflags=" "-X main.Version=${rev}" ];
  buildInputs = [ pkgs.go-bindata ];

  preBuild = ''
    cd go/src/${goPackagePath}

    count=0
    mkdir -p include
    touch include/buildpacks.txt
    for i in multi ruby nodejs clojure python java gradle scala play php go static; do \
    		bp_count=$(printf '%02d' $count) ;
    		echo -n "$bp_count"_buildpack-"$i " ;
    		cat buildpacks/*-$i/buildpack* | sed 'N;s/\n/ /';
    		count=$((count + 1)) ;
    	  done > include/buildpacks.txt

	  go-bindata include
  '';

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    homepage = http://gliderlabs.github.io/devlog/;
    description = "Utility for emulating Heroku build and runtime tasks in containers";
    license = licenses.mit;
    platforms = platforms.linux;
    maintainers = with maintainers; [
      WhittlesJr
    ];
  };
}
