# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/kardianos/osext";
    fetch = {
      type = "git";
      url = "https://github.com/kardianos/osext";
      rev = "ae77be60afb1dcacde03767a8c37337fad28ac14";
      sha256 = "056dkgxrqjj5r18bnc3knlpgdz5p3yvp12y4y978hnsfhwaqvbjz";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "af06845cf3004701891bf4fdb884bfe4920b3727";
      sha256 = "0ydzkipf28hwj2bfxqmwlww47khyk6d152xax4bnyh60f4lq3nx1";
    };
  }
  {
    goPackagePath = "github.com/progrium/go-basher";
    fetch = {
      type = "git";
      url = "https://github.com/progrium/go-basher";
      rev = "6a5b35fcdaea1ddfc145720efc903869413629e7";
      sha256 = "0g8819lj2x45wl96yw6v69i30ln9yicg6wlrl8cvh34h0v9jx3rc";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "51d6538a90f86fe93ac480b35f37b2be17fef232";
      sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa";
    };
  }
]
