# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "tsuru-client-${version}";
  version = "1.6.0";
  rev = "${version}";

  goPackagePath = "github.com/tsuru/tsuru-client";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/tsuru/tsuru-client";
    sha256 = "0sjvfc8dmb1blh8w1ax01ybprb7knxxz4zs2dnlkqlwcyxgy5518";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    homepage = https://docs.tsuru.io;
    description = "A tsuru command line tool for application developers.";
    license = licenses.bsd-3;
    platforms = platforms.linux;
    maintainers = with maintainers; [
      WhittlesJr
    ];
  };
}
