# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/tsuru/tsuru";
    fetch = {
      type = "git";
      url = "https://github.com/tsuru/tsuru.git";
      rev = "ee830245fc632cab1d71e697bdb45aa1bd3697a9";
      sha256 = "1crji5slnmxcd75i5n1k0q6spslixiar0cbabyc08yvb59a77drr";
    };
  }
]
