# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gandalf-${version}";
  version = "0.7.3";
  rev = "${version}";

  goPackagePath = "github.com/tsuru/gandalf";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/tsuru/gandalf.git";
    sha256 = "1y29l67n3nmgys8628bs5vk3k2p1b6yhph54bgkcclkjk49r6vf8";
  };

  goDeps = ./deps.nix;

  postInstall = ''
    mv $bin/bin/bin $bin/bin/gandalf-ssh
    mv $bin/bin/webserver $bin/bin/gandalf-webserver
  '';

  meta = with stdenv.lib; {
    homepage = https://gandalf.readthedocs.io/en/latest/;
    description = "Gandalf is an HTTP API for managing Git repositories.";
    license = licenses.bsd-3;
    platforms = platforms.linux;
    maintainers = with maintainers; [
      WhittlesJr
    ];
  };
}
