# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
# Modified dep versions by hand to match Godeps.json
[
  {
    goPackagePath = "github.com/codegangsta/negroni";
    fetch = {
      type = "git";
      url = "https://github.com/codegangsta/negroni";
      rev = "a13766a8c2572caeb14341b7de158aff2fd00fa9";
      sha256 = "0iyy45c326h3wq7xkc0gg0rzi4n88f76hmii9rgh3ddf4xhnv3hv";
    };
  }
  {
    goPackagePath = "github.com/gorilla/context";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/context";
      rev = "708054d61e5a2918b9f4e9700000ee611dcf03f5";
      sha256 = "05sdv5331ha192zbrxbjj03zrhx4rb75glgbajr5xlcdq50dczh7";
    };
  }
  {
    goPackagePath = "github.com/gorilla/mux";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/mux";
      rev = "4b8fbc56f3b2400a7c7ea3dba9b3539787c486b6";
      sha256 = "0wx6m2w6wfwzmn573j02jfb33i0fx4hwv4iha67bckx97zma0x92";
    };
  }
  {
    goPackagePath = "github.com/gorilla/pat";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/pat";
      rev = "ae2e162c4b2ae96aa66b596b2c18f17834299ed0";
      sha256 = "0zrwwcgaa6y88nv2d84rz89knc27d6ly09xvk31bn6af2ha7pmb0";
    };
  }
  {
    goPackagePath = "github.com/howeyc/fsnotify";
    fetch = {
      type = "git";
      url = "https://github.com/howeyc/fsnotify";
      rev = "5102fde921d31f59c6e45d835aa01f0213aade0f";
      sha256 = "16lp2p29rkcw03bz9jjfyg6x1saiqfikh4wvli3avx80wlsyki3d";
    };
  }
  {
    goPackagePath = "github.com/tsuru/config";
    fetch = {
      type = "git";
      url = "https://github.com/tsuru/config";
      rev = "cedd0ae4817d94ddda2b1320f3a8c9154c4d0d57";
      sha256 = "1yr9841i3rqpimy98779ins0j3i758aa3ycfy72wmdydmfqhsqsa";
    };
  }
  {
    goPackagePath = "github.com/tsuru/tsuru";
    fetch = {
      type = "git";
      url = "https://github.com/tsuru/tsuru.git";
      rev = "79f9c6ff297984b6a27f99c2c71c534f203a4cc4";
      sha256 = "0pj7v0sdf8al6wghdxqva97cc6gq0vp0inmviwz9hhir7q372vjr";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "1fbbd62cfec66bd39d91e97749579579d4d3037e";
      sha256 = "0w4galaq43qjdcbpw9vxw1cdk5ldzj095raq7rzg5isw9qxwrv5i";
    };
  }
  {
    goPackagePath = "gopkg.in/mgo.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/mgo.v2";
      rev = "3569c88678d88179dcbd68d02ab081cbca3cd4d0";
      sha256 = "0xax7208pqs840hs6zc0907j35dcam5x5qwg48j301rxj0gmabcr";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v1";
      rev = "4914593b9558e85597f08346c798aea8f6fb899f";
      sha256 = "0fdprm61f6ddkmzjy64a9584mh5jsw3k45plb94dn4fxcjxrl5l0";
    };
  }
]
